name 'audit_time_window'
maintainer 'Matt Ray'
maintainer_email 'matt@chef.io'
license 'Apache-2.0'
description 'Manages restricting InSpec profiles via the audit cookbook to a time window'
version '0.1.0'
chef_version '>= 14.0'

issues_url       'https://github.com/mattray/audit_time_window-cookbook/issues'
source_url       'https://github.com/mattray/audit_time_window-cookbook'
